/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Side: "buy" | "sell";
        /** @enum {string} */
        OrderType: "limit" | "market";
        /** @enum {string} */
        OrderStatus: "accepted" | "rejected" | "open" | "amended" | "partially_filled" | "filled" | "cancelled" | "expired" | "locked_non_cancellable";
        /** @enum {string} */
        SessionStatus: "closed" | "pre_open" | "opening_auction" | "continuous" | "pre_close" | "random_closing" | "closing_auction" | "non_cancellation" | "post_closing" | "halted";
        Order: {
            id: string;
            client_order_id: string;
            broker_code: string;
            account_id: string;
            symbol: string;
            side: components["schemas"]["Side"];
            order_type: components["schemas"]["OrderType"];
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            original_quantity: number;
            /** Format: int64 */
            remaining_quantity: number;
            /** Format: int64 */
            filled_quantity: number;
            status: components["schemas"]["OrderStatus"];
            reject_reason?: string;
            idempotency_key?: string;
            /** Format: int64 */
            sequence_number: number;
            correlation_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Trade: {
            id: string;
            /** Format: int64 */
            sequence_number: number;
            session_id: string;
            symbol: string;
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            quantity: number;
            buy_order_id: string;
            sell_order_id: string;
            buy_broker_code: string;
            sell_broker_code: string;
            buy_account_id: string;
            sell_account_id: string;
            /** Format: date-time */
            occurred_at: string;
            idempotency_key: string;
        };
        MarketSummary: {
            symbol: string;
            /** Format: int64 */
            open: number;
            /** Format: int64 */
            high: number;
            /** Format: int64 */
            low: number;
            /** Format: int64 */
            close: number;
            /** Format: int64 */
            last: number;
            /** Format: int64 */
            volume: number;
            /** Format: int64 */
            value: number;
            /** Format: int64 */
            frequency: number;
        };
        BookLevel: {
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            quantity: number;
            orders: number;
        };
        BookSnapshot: {
            symbol: string;
            bids: components["schemas"]["BookLevel"][];
            asks: components["schemas"]["BookLevel"][];
        };
        IndicativePriceVolume: {
            symbol: string;
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            volume: number;
            /** Format: int64 */
            imbalance: number;
            /** Format: int64 */
            reference_price: number;
            /** Format: date-time */
            calculated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
